apiVersion: v1
kind: Pod
metadata:
  name: jbang-script
  labels:
    app: jbang-script
spec:
  containers:
    - name: jbang-script
      image: jbangdev/jbang-action
      env:
        - name: INPUT_SCRIPT
          value: /scripts/script.java
      volumeMounts:
        - name: scripts
          mountPath: /scripts
  volumes:
    - name: scripts
      configMap:
        name: jbang-script
  restartPolicy: Never
